<a href="https://colab.research.google.com/github/NarutoVaibhav/image-classification/blob/main/Image_Classification1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ipython-autotime
%load_ext autotime

time: 2.29 ms (started: 2021-03-30 14:30:32 +00:00)


In [ ]:
# Data :Images 
#Use Python libraries to scrape the images (Using)

time: 1.71 ms (started: 2021-03-30 14:31:01 +00:00)


In [ ]:
!pip install bing-image-downloader

time: 3.13 s (started: 2021-03-30 14:31:31 +00:00)


In [ ]:
!mkdir images

time: 120 ms (started: 2021-03-30 14:32:19 +00:00)


In [ ]:
from bing_image_downloader import downloader
downloader.download("rugby leather ball",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://cdn.notonthehighstreet.com/system/product_images/images/000/393/351/original_CF016852.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://cdn.shopify.com/s/files/1/0788/5979/products/mvp-leather-balls-heritage-leather-rugby-ball-1_1024x1024.jpg?v=1550134680
[%] File Downloaded !

[%] Downloading Image #3 from https://www.john-woodbridge.com/1536-tm_large_default/leather-vintage-football-allen-1938.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://images.antiquesatlas.com/dealer-stock-images/puckeringsantiques/Antique_Novelty_Travel_Inkwell_as584a1568z-3.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://cdn.shopify.com/s/files/1/0020/1025/1324/products/32p_black_1024x.png?v=1534865418
[%] File Downloaded !

[%] Downloading Image #6 from https://cdn.thinglink.me/api/image/586569159714799617/1240/10/scaletowidth
[%] File Downloaded !

[%] Downloading Im

In [ ]:
from bing_image_downloader import downloader
downloader.download("aeroplane",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://i.ytimg.com/vi/qz1RREH-IBo/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.masterwishmakers.com/wp-content/uploads/2014/08/kids-airplane-room.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://i.ytimg.com/vi/_hSrNMX5Fig/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://hative.com/wp-content/uploads/2014/03/transport-paper-roll-crafts/9-homemade-airplanes.JPG
[%] File Downloaded !

[%] Downloading Image #5 from https://i.ytimg.com/vi/iGtZHHj2w4U/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.fonewalls.com/wp-content/uploads/1242x2688-Background-HD-Wallpaper-024-300x649.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.ytimg.com/vi/7iOOiYmSOt8/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://i.ytimg.com/vi/LMTcQ8f1QO4/maxresdefault.jpg

In [ ]:
from bing_image_downloader import downloader
downloader.download("cruise",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://www.canadianaffair.com/images/canada/british-columbia/vancouver/VAN018/fairmont-hotel-vancouver/gall-e/max/yvrcp-exterior-003.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://thumbs.dreamstime.com/x/pharaoh-ramses-ii-ancient-king-egypt-1388113.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://www.tourismbonaire.com/includes/images/gallery/BonaireCaribbean_24.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.disneyeveryday.com/wp-content/uploads/2015/11/FinnTFA.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.hdwallpapers.in/download/godafoss_waterfalls_iceland-1280x800.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://funnypost.in/wp-content/uploads/2016/08/Funny-Pic-12-560x994.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://www.movienewz.com/img/gallery/upside-down/photos/upside_down_2.jpg
[%]

In [ ]:
# Preprocessing
# 1. Resize
# 2. Flatten

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = '/content/images'
CATEGORIES = ['rugby leather ball','aeroplane','cruise']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category) # Label Encoding the values
  path = os.path.join(DATADIR,category) # Create path to use all the images
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)
    img_resized = resize(img_array,(150,150,3)) # Normalizes the value from 0 to 1
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)


time: 19.8 s (started: 2021-03-30 14:41:58 +00:00)


In [ ]:
len(flat_data[0])

67500

time: 4.63 ms (started: 2021-03-30 14:42:40 +00:00)


In [ ]:
150*150*3

67500

time: 4.48 ms (started: 2021-03-30 14:43:00 +00:00)


In [ ]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

time: 8.39 ms (started: 2021-03-30 14:43:11 +00:00)


In [ ]:
unique,count = np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

<BarContainer object of 3 artists>

time: 166 ms (started: 2021-03-30 14:43:48 +00:00)


In [ ]:
# Split data into Training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,
                                  test_size=0.3,random_state=109)

time: 233 ms (started: 2021-03-30 14:44:13 +00:00)


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 1min 38s (started: 2021-03-30 14:44:45 +00:00)


In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 144 ms (started: 2021-03-30 14:54:23 +00:00)


In [ ]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 5.45 ms (started: 2021-03-30 14:54:43 +00:00)


In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 1.34 ms (started: 2021-03-30 14:55:00 +00:00)


In [ ]:
accuracy_score(y_pred,y_test)

1.0

time: 5.33 ms (started: 2021-03-30 14:55:19 +00:00)


In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 8,  0,  0],
       [ 0, 11,  0],
       [ 0,  0,  8]])

time: 6.29 ms (started: 2021-03-30 14:55:36 +00:00)


In [ ]:
# Save the model using Pickle library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 34.2 ms (started: 2021-03-30 14:56:18 +00:00)


In [ ]:
model = pickle.load(open('img_model.p','rb'))

time: 24 ms (started: 2021-03-30 14:56:34 +00:00)


In [ ]:
# Testing a brand new Image
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')

Enter your URLhttps://www.aljazeera.com/wp-content/uploads/2020/12/2020-12-09T114554Z_1329857512_RC2NJK98FXB2_RTRMADP_3_HEALTH-CORONAVIRUS-SINGAPORE-CRUISESHIP.jpg
(4480, 6720, 3)
 PREDICTED OUTPUT: cruise


time: 3min 30s (started: 2021-03-30 14:57:02 +00:00)


In [ ]:
!pip install streamlit

!pip install pyngrok
from pyngrok import ngrok

     |████████████████████████████████| 7.0MB 6.3MB/s 
     |████████████████████████████████| 163kB 42.2MB/s 
     |████████████████████████████████| 4.6MB 44.3MB/s 
     |████████████████████████████████| 112kB 43.3MB/s 
     |████████████████████████████████| 81kB 4.2MB/s 
     |████████████████████████████████| 71kB 5.4MB/s 
     |████████████████████████████████| 122kB 39.7MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13448 sha256=789dd22f08ad1e5916ea0829c10e931934201ba1a798f4984bbc9a8e273ce218
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.0 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


     |████████████████████████████████| 747kB 6.2MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.5-cp37-none-any.whl size=19246 sha256=cea4f51aae3bbf21974fe1e3ac50d9da615e235bc3d413ab1020d69f9eeebf92
  Stored in directory: /root/.cache/pip/wheels/0c/13/64/5ebbcc22eaf53fdf5766b397c1fb17c83f5775fdccf0ea1b88
Successfully built pyngrok
time: 20 s (started: 2021-03-30 15:01:00 +00:00)


In [ ]:
#Deployement

In [ ]:
%%writefile app.py
import streamlit as st
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle 
from PIL import Image
st.set_option('deprecation.showfileUploaderEncoding', False)
st.title('Image Classifier using Machine Learning')
st.text('Upload the Image')

model = pickle.load(open('img_model.p','rb'))

uploaded_file = st.file_uploader("Choose an image...", type="jpg")
if uploaded_file is not None:
  img = Image.open(uploaded_file)
  st.image(img,caption='Uploaded Image')

  if st.button('PREDICT'):
    CATEGORIES = ['rugby leather ball','aeroplane','cruise']
    st.write('Result...')
    flat_data=[]
    img = np.array(img)
    img_resized = resize(img,(150,150,3))
    flat_data.append(img_resized.flatten())
    flat_data = np.array(flat_data)
    y_out = model.predict(flat_data)
    y_out = CATEGORIES[y_out[0]]
    st.title(f' PREDICTED OUTPUT: {y_out}')
    q = model.predict_proba(flat_data)
    for index, item in enumerate(CATEGORIES):
      st.write(f'{item} : {q[0][index]*100}%')


Writing app.py
time: 4.38 ms (started: 2021-03-30 15:02:38 +00:00)


In [ ]:
!nohup streamlit run app.py &

url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


<NgrokTunnel: "http://b181e55e3314.ngrok.io" -> "http://localhost:80">

time: 1.93 s (started: 2021-03-30 15:02:55 +00:00)
